#!/bin/sh

setxkbmap -layout us,ch -option grp:shifts_toggle &
xset r rate 200 20 &

# Mouse speed
xset m 3/2 4 &

# speed second mouse logitech usb:
xinput set-prop "Logitech USB Optical Mouse" "Device Accel Constant Deceleration" 0.3
