#!/bin/sh
# xrandr --output DP-2-1 --off --output DP-2-2 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-2-3 --off --output eDP-1 --off --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off
xrandr --output DP-2-1 --mode 2560x1440 --pos 0x0 --rotate left --output DP-2-2 --mode 2560x1440 --pos 1440x544 --rotate normal --output DP-2-3 --off --output eDP-1 --off --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off

