#!/bin/sh

. `dirname $0`/monitors

# first enable second monitor
xrandr  $turnoff_unusd \
  --output $l1_interface --primary --mode $l1_resolution --pos 0x0 --rotate normal \
  --output $m2_interface --off \
  --output $m3_interface --off \
  --output $m4_interface --off

fix_i3_issues
