#!/bin/sh
xrandr --setprovideroutputsource 1 0
xrandr --setprovideroutputsource 2 0

xrandr --output eDP1 --mode 2560x1600 --pos 0x0 --rotate normal
xrandr --output DVI-1-0 --off --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DVI-2-1 --off --output DP2 --off

xrandr --dpi 184
