#!/bin/sh
xrandr --setprovideroutputsource 1 0
xrandr --setprovideroutputsource 2 0

xrandr --output DVI-1-0 --mode 1680x1050 --pos 0x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output eDP1 --off --output DVI-2-1 --mode 1680x1050 --pos 1680x0 --rotate normal --output DP2 --off

xrandr --dpi 96
i3-msg restart

# mouse speed
xinput set-prop "USB Optical Mouse" "Device Accel Constant Deceleration" 0.3
xinput --set-button-map "USB Optical Mouse" 1 2 3 5 4
